name: background
description: Background service
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^9.1.1

flutter:
  plugin:
    platforms:
      android:
        package: tld.domain.background
        pluginClass: BackgroundPlugin
